julianxhokaxhiu/FFNx

misc/FFNx.cfg
src/cfg.cpp
src/cfg.h
src/common.cpp
src/common.h
src/directmusic.h
src/externals_102_de.h
src/externals_102_fr.h
src/externals_102_sp.h
src/externals_102_us.h
src/ff7.h
src/ff7_opengl.cpp
src/ff8.h
src/ff8_data.h
src/ff8_opengl.cpp
src/music.cpp
src/music.h
src/winamp/music.cpp
src/winamp/music.h
src/winamp/plugin.cpp
src/winamp/plugin.h

Implements external music plugin for FF8.

FF8 External Music

---

src/winamp/in_vgmstream.cpp
src/winamp/music.cpp
src/winamp/plugin.cpp
src/winamp/plugin.h

- Cleaning in_vgmstream code by removing ini configuration functions
- Adding failback to ogg

Music plugin improvements

---

src/winamp/music.cpp

Because infinite loop should be always enabled

Do not restart a music when song reached end

---

README.md
misc/FFNx.cfg
src/cfg.cpp
src/cfg.h
src/movies.cpp

- Starting to Make the config Cleaner and Easier to read.

Cleaner Config File

---

misc/FFNX.overlay.frag
misc/FFNX.overlay.vert
misc/FFNx.cfg
src/CMakeLists.txt
src/cfg.cpp
src/cfg.h
src/common.cpp
src/common.h
src/ff7.h
src/ff7_data.h
src/ff7_opengl.cpp
src/ff8.h
src/ff8_data.h
src/imgui/imconfig.h
src/imgui/imgui.cpp
src/imgui/imgui.h
src/imgui/imgui_demo.cpp
src/imgui/imgui_draw.cpp
src/imgui/imgui_internal.h
src/imgui/imgui_widgets.cpp
src/imgui/imstb_rectpack.h
src/imgui/imstb_textedit.h
src/imgui/imstb_truetype.h
src/input.cpp
src/input.h
src/overlay.cpp
src/overlay.h
src/renderer.cpp
src/renderer.h

- Merged some keyboard externals into common
- Removed a DInput patch as that function is now replaced
- Added event listener functionality
- Added WindowProc proxy
- Added ability to block game from receiving keyboard input
- Added ImGui for debug windows

Added, ImGui, input listeners, WindowProc proxy and keyboard blocking

---

src/common.cpp
src/ff8.h
src/ff8_data.h
src/overlay.cpp
src/world.cpp
src/world.h

Added imgui world debug section for worldmap
Features:
- camera zoom
- player position
- collision disable/enable
- current colliding triangle full debug and editing including flags

FF8: world debug options

---

misc/FFNx.toml
src/audio.cpp
src/audio.h
src/audio/openpsf/openpsf.cpp
src/cfg.cpp
src/cfg.h

#129 Allow multiple extensions for external_sfx/music/voice

---

src/audio.cpp
src/audio.h
src/ff8.h
src/ff8_data.h
src/music.cpp

Using the name "eyes_on_me", like the Steam version.

FF8: Adding support for Eyes On Me in external_music

---

misc/FFNx.field.shadow.frag
misc/FFNx.field.shadow.vert
misc/FFNx.lighting.frag
misc/FFNx.lighting.sh
misc/FFNx.lighting.vert
misc/FFNx.pcf.sh
misc/FFNx.shadowmap.frag
misc/FFNx.shadowmap.vert
misc/FFNx.toml
misc/FFNx.varying.flat.def.sc
misc/FFNx.varying.smooth.def.sc
src/CMakeLists.txt
src/cfg.cpp
src/cfg.h
src/common.cpp
src/ff7/graphics.cpp
src/field.cpp
src/gl.h
src/gl/deferred.cpp
src/gl/gl.cpp
src/gl/special_case.cpp
src/lighting.cpp
src/lighting.h
src/lighting_debug.cpp
src/lighting_debug.h
src/overlay.cpp
src/overlay.h
src/renderer.cpp
src/renderer.h

- Implemented vertex normal calculation by averaging adjacent triangle normals
- Implemented physically-based lighting with diffuse and Cook-Torrance specular BRDF
- Implemented real-time shadows through shadow maps
- Implemented OptimizedPCF method to remove shadow aliasing / create soft shadows
- Implemented deferred draw calls for most scene models
- Improved shadow map setup by setting frustum target to the scene AABB center
- Implemented character field shadows by projecting 3D models into the walkmesh
- Implemented method that extrudes the walkmesh to fade out sharp shadow discontinuities
- Implemented field shadow fade out with distance from occluder to the walkmesh floor
- Added ImGui window for adjusting parameters and debugging
- Improved field shadows using the stencil buffer …

Implemented real-time lighting and shadow option

---

misc/FFNx.field.shadow.frag
misc/FFNx.field.shadow.vert
misc/FFNx.pcf.sh

Fixed the field shadow distance fade implementation that got broken during after reverting changes in the previous PR.
This mostly fixes weird shadows appearing in multi-level fields.
https://clips.twitch.tv/InquisitiveElegantPancakeJKanStyle-jaJFSdEWfTMiwSLK

Fixed field shadow distance fade

---

src/gl/gl.cpp

I removed the double nested for loop so it should be faster now.

Optimized normal calculation

---

misc/FFNx.lighting.frag

This fixes a mistake I made when processing the PBR textures in the lighting shader. I also removed unnecessary code I used for debug.

Fixed incorrect processing of PBR textures

---

misc/FFNx.lighting.vert
src/common.cpp
src/gl.h
src/gl/deferred.cpp
src/lighting.cpp
src/renderer.cpp
src/renderer.h

Fixed the field shadows being drawn over the 3d models. I also removed all the stencil buffer related API since those are not needed anymore.

Fixed field shadows being drawn over 3D models

---

src/renderer.cpp

If fixed some black screen problems that have been reported lately.

Fixed black screen problems whith lighting enabled

---

misc/FFNX.overlay.vert
misc/FFNx.common.sh
misc/FFNx.frag
misc/FFNx.lighting.frag
src/lighting.h
src/renderer.cpp

Fixed transparency by performing blending in SRGB space. Lighting is still being done in linear space as I wanted, only blending is done in SRGB so that it looks exactly the same as before.

Fixed transparency by performing blending in SRGB space

---

CMakeSettings.json
src/achievement.cpp
src/achievement.h
src/ff7/misc.cpp
src/movies.cpp

Move the check of unlocking the game progress achievement at the end of a movie or after skipping a movie

FF7Achievement: improve UX of game progress achievement and update CMakeSettings.json

---

src/achievement.cpp
src/achievement.h
src/ff7_opengl.cpp
src/movies.cpp

In the end, there was no bug, so there is nothing else to add. I don't have anything else to add.

FF7Achievement: Refactor getLastSeenMovieName to isEndingMovie

---

misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff7.h
src/ff7_data.h
src/voice.cpp

- Add flag variable for battle text/dialogue in cfg and toml
- Replace function that add text to be displayed
- Replace function that updates the text data to be displayed

Voice: Add backbone for voiced battle dialogue

---

src/achievement.cpp
src/achievement.h
src/ff7.h
src/ff7/menu.cpp
src/ff7_data.h
src/voice.cpp

- Add decoding text in readable text
- Add get enemy id for battle voices file name
- Fix correct name for scene id into formation id

Voice: Improve battle voices support

---

src/voice.cpp

Also refactor some variable names for consistency with the file

Voice: Replace hash with dialog text as filename

---

src/common.cpp
src/ff7.h
src/ff7/defs.h
src/ff7/misc.cpp
src/ff7_data.h
src/sfx.cpp
src/voice.cpp

Try to see if the pause truly does not work. I tried it and it seems that after pausing the voice was still going a little. Then after resuming it started a lot afterwards

Voice: Fix pause and music fadeout logics

---

src/music.cpp

~Untested since the last canary has some bugs which prevent progression in the game~
Thoses bug aren't present when compiling FFNx in Release mode

FF7: customize minigame music

---

src/ff7.h
src/ff7/camera.cpp
src/ff7/field.cpp
src/ff7/world.cpp
src/ff7_data.h
src/ff7_opengl.cpp
src/movies.cpp
src/sfx.cpp

With this, I think we are ready to release it

60FPS: Fix FIELD, WORLD, BATTLE animation bugs and glitches

---

src/common.cpp
src/ff7.h
src/ff7/animations.cpp
src/ff7/camera.cpp
src/ff7/field.cpp
src/ff7/world.cpp
src/ff7_data.h
src/ff7_opengl.cpp
src/globals.h
src/movies.cpp
src/voice.cpp

I also made a fix on Aali layer2pick_tiles. From what I tested, nothing seems to change.

60FPS: Add full support for SWIRL mode

---

CMakeLists.txt
misc/FFNx.lighting.toml
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/common.cpp
src/gl.h
src/gl/gl.cpp
src/lighting.cpp
src/lighting.h
src/renderer.cpp

In the lighting you can change some parameters that could only be changed before from the debug window. Also it contains a list of textures used by models such a skyboxes that should not be rendered with lighting.

Added lighting config file

---

src/lighting.cpp
src/lighting.h

Optimized walkmesh shadow calculations to be done only once when changing fields.

Optimized walkmesh shadow calculations to be done only once per field

---

src/audio.cpp
src/common.cpp
src/ff7/defs.h
src/ff7/misc.cpp
src/hext.cpp
src/utils.h
src/voice.cpp

- Fix voice volume not being set when using character action voices
- Fix rerouting of voice filenames
- Move voice battle pause and resume mechanism in common_flip like ambient sounds

Voice: Fix BATTLE character action voices bugs

---

src/ff7.h
src/ff7/world.cpp
src/ff7_data.h
src/ff7_opengl.cpp
src/sfx.cpp
src/sfx.h

The goal is to add a loop sound to highwind and then change it like Tiny Bronco (changing the pitch???) when it's moving. Or maybe we could only add sound when highwind is moving

FF7: Improve worldmap footsteps + Add worldmap highwind sound

---

src/ff7/field.cpp
src/movies.cpp
src/movies.h

Also refactor MOVIE FPS fix by moving it all into ff7/field.cpp

60FPS: Fix Great Glacier counter steps before fainting

---

src/ff7/field.cpp

Since there could be other special occasion in which the previous rotation movement logic had issues, I redid the
new rotation movemeng logic by removing all the hooks where rotation steps are set. Instead, the only modification
is on the rotation update where the increment of the steps index is done only every 2 frame in 60FPS.
This solution is much simpler and less prone to bugs and glitches.

60FPS: Rework the 60FPS rotation movement logic

---

src/achievement.cpp
src/achievement.h
src/ff7.h
src/ff7_data.h
src/voice.cpp

Also there was some warning on log telling that some externals were already defined. So I cleaned up those.

FF7Achievement: Fix some bugs about cait sith and emerald weapon

---

Changelog.md
src/ff7.h
src/ff7/field.cpp
src/ff7_data.h

Plus refactor some variable names

60FPS: Implement smooth movement for cursor and arrows in FIELD mode

---

misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/common.cpp
src/common.h
src/renderer.cpp

This PR changes the aspect ratio variable to allow for multiple modes.

Changed aspect ratio variable to allow multiple modes

---

Changelog.md
src/audio.cpp
src/audio.h
src/ff8.h
src/ff8_data.cpp
src/sfx.cpp

FF8: SFX external

---

misc/FFNx.frag

Fixed incorrect conditional from the previous PR.
To fix bug that was occurring even when day-night system was disabled.

FF7: Fixed incorrect time cycle filter conditional

---

README.md

General consistency clean-up and overall update of the README
Bonez found a grammar bug
Not Applicable

Gardening: Update README.md

---

Changelog.md
src/ff8.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/music.cpp
src/utils.cpp
src/utils.h

- Some graphical glitches appear when using the Tonberry compatibility layer.
- Some textures are missing in battle when using external textures

FF8: better tonberry compatibility

---

src/ff8/field/chara_one.cpp
src/ff8_data.cpp

FF8: Fix crash in non-US versions

---

src/ff8/uv_patch.cpp
src/ff8_data.cpp
src/voice.cpp
src/world.cpp

FF8: Fix crash from PR #601

---

misc/FFNx.frag
misc/FFNx.lighting.frag

Fixed fog rendering not working in underwater worldmap.
To wrap things up before my girlfriend comes back home.

FF7: Fixed fog rendering not working in underwater worldmap

---

Changelog.md
src/common.cpp
src/ff8.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp

Related to #29 
Some textures was not correctly detected.

FF8: allow external textures from magic.fs

---

Changelog.md
src/ff8/mod.cpp
src/ff8/mod.h

FF8: Fix texture animation only partially animated - part 2

---

src/gl/gl.cpp

Fix for the previous PR.
To make Satsuki happy and save the planet.

FF7: Fix movie aspect ratio in true widescreen mode

---

src/ff8_opengl.cpp

FF8: Fix intro credits not showing properly

---

Changelog.md
src/ff8.h
src/ff8_data.cpp
src/field.cpp

FF8: Fix jp version crash

---

README.md

Fix documentation for building directly using cmake
Help other neovim lovers!

Gardening: Update README.md for Neovim section

---

src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp

Fix crashes on game start for non-us versions
- N/A I have updated the [Changelog.md](https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md) file

FF8: Fix crashes in non-US versions
