README.md

A few people on Discord (myself included) were having issues with assuming we were supposed to be replacing all instances of the `7H_GameDriver.dll` file and that the only purpose of step 3 was just for a backup. Having the renamed filed in the driver folder prevents 7H from running the game. Hoping this adds a little extra clarity. Feedback on Discord? `@Hugin#8484`

Tweaked the 7Hv2 install directions a tad for added clarity

---

src/common.cpp

If the user has set a path check if we can open that path and we if can ensure our plugin is set correctly .. This happens before our other checks so our defaults will now acts as a fallback as an added bonus.

Set plugin if music path is set

---

misc/FFNx.cfg
src/cfg.cpp
src/cfg.h
src/common.cpp
src/ff8_opengl.cpp

Change the var use_external_movie => enable_ffmpeg_videos
this User facing change is pre-cursor to a configuration clean up i plan to do later. The config option was changed to more clearly reflect what it does.

Rename use_external_movie => enable_ffmpeg_videos

---

src/common.h
src/externals_102_de.h
src/externals_102_fr.h
src/externals_102_sp.h
src/externals_102_us.h
src/ff7.h
src/music.cpp
src/music.h
src/winamp/music.cpp
src/winamp/music.h

Adding ability to replace the wav files (FF7 only)
Fix a music bug in the game: the "lock music" instruction is cleared on field changes, but "lock music" should be persistent across fields. This fixes:
- music stop bug in the first scene with Reno and Aerith
- Battle music restarted after the fight against Rufus
- Underneath the rotting pizza intervention after the movie with Sephiroth in fire
- more scenes I haven't tested involving MUSCLCK opcode (in space for example)
Possible consequence: if fields scripts does not unlock music correctly, a music could be played for too long in wrong scenes.

Feature/wav in winamp plugin + music lock patch

---

misc/FFNx.cfg

Removed the 
#~~~~~~~~~~~~~~~ 
before the description. these lines are now only after the description and before the option. This should make it easier to see where the option goes more easily

Clean up cfg style to be more readable

---

src/ff7.h
src/ff7/defs.h
src/ff7/field.cpp
src/ff7_data.h
src/ff7_opengl.cpp

flevel.lgp/flevel.siz contains the uncompressed sizes of the LZSed field map files.
The current implementation uses this file to allocate enough memory to uncompress the field. It adds 2000000 to this value, just to be safe.
But not matters how long is flevel.siz, the parser always read 387 entries (aka the field map count). The game initialize 1200 (see sub_60EEB2) entries of the field info structure (where the uncompressed size is stored), so we should be safe to increase this limitation.

Replace open_flevel_siz method with a more flexible implementation

---

src/sfx.cpp
src/sfx.h

There is two volume levels: the one (per channel) from the original game (from 0 to 127) and a master level (only in the PC version) which can be modified via the configuration menu.
The final volume is computed like this: master * volume[channel] / 100.
The set_sfx_volume (on channel) method has a bad behavior: it set the sfx state with the result of this volume, but everytime the state is used, the computation above is computed... again!
Instead of removing computations when the state is used, I chose to force the value of the state in set_sfx_volume directly.

Fix inconsistent sfx volume

---

src/common.h
src/externals_102_de.h
src/externals_102_fr.h
src/externals_102_sp.h
src/externals_102_us.h
src/ff7.h
src/ff7_data.h
src/music.cpp
src/music.h
src/sfx.cpp
src/sfx.h

- Play music in Game Over Screen when the timer reached zero in the first mission
- Fix summon sfx volume (user SFX volume wasn't applied)
- Fix Leviathan sound stopped early
- Fix Omnislash sound not loaded

Fix lots of SFX bugs (FF7)

---

README.md
misc/FFNx.music.toml
src/CMakeLists.txt
src/audio.cpp
src/audio.h
src/audio/openpsf/openpsf.cpp
src/audio/vgmstream/vgmstream.cpp
src/ff8.h
src/ff8_data.h
src/music.cpp

Example of a configuration file:
~~~toml
[joriku]
no_intro_track = 'joriku2'
[joriku2]
offset_seconds = 51.8
[gargarde]
no_intro_track = 'gar3'
[hikutei]
intro_seconds = 21
~~~
- no_intro_track: track name of the music without intro if "no intro" is detected (the game already do it for joriku)
- offset_seconds: play the track at this value, instead of from the begining (only useful because I don't have a proper joriku2 psf without intro for now)
- intro_seconds: how many seconds to skip when the track is played without intro

Adding music skip configuration entries + implement opcode_musicskip and opcode_getmusicoffset

---

src/cfg.cpp

It was broken in d05a902fed5a3bf3bba2417617463ca10797f8b3.

Fixed license boilerplate

---

src/music.cpp

Tiny fix to make this feature also available for native midis

FF8: Pause/resume music and SFX when pausing the game in field

---

src/gl.h
src/gl/deferred.cpp
src/lighting.cpp

This is the fix for the problem reported by Kaldarasha about the field shadows being drawn over the light overlay found in some places such as the Forgotten City. I fixed it by drawing first the opaque objects, then the field shadows, then non-opaque objects.

Fixed field shadows being drawn over the light overlay

---

misc/FFNx.frag
misc/FFNx.lighting.frag
misc/FFNx.lighting.sh
misc/FFNx.lighting.vert
misc/FFNx.shadowmap.frag
misc/FFNx.shadowmap.vert
misc/FFNx.varying.flat.def.sc
misc/FFNx.varying.smooth.def.sc
misc/FFNx.vert
src/common.cpp
src/gl.h
src/gl/gl.cpp
src/lighting.cpp
src/lighting.h
src/lighting_debug.cpp
src/renderer.cpp
src/renderer.h

Added support for extended PBR textures (normal map, roughness, metalness, AO). This is achieved by extending the textures vertically to three times their original height. The first region contains the original texture, the second contains the normal map (RGB channels, alpha unused), the third region contains the other parameters (R: roughness, G: metalness, B: AO, A unused). These extended textures will be provided in IRO mods.
The core FFNx was slightly changed to make it work with the extended textures mods even when lighting is off (otherwise the uvs would be broken and cause the extended textures to show as colors).

Added support for extended PBR textures

---

.gitignore
.idea/.gitignore
.idea/.name
.idea/FFNx.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
CMakeLists.txt

There is not really a clion project file. Because Clion's settings will be different for everyone. As adding visual studio's compiler is a manual process. So these changes are more for helping future users.
These are fatal errors to stop them as soon as possible. Provide some tips how to fix the issue. I think devel is a good value `_DLL_VERSION`.
added this to CMakeLists.txt
```cmake
if(DEFINED CMAKE_BUILD_TYPE AND CMAKE_BUILD_TYPE) # Azure and multi-configuration generators don't set CMAKE_BUILD_TYPE
if (NOT CMAKE_BUILD_TYPE MATCHES Release AND NOT CMAKE_BUILD_TYPE MATCHES RelWithDebInfo)
message(FATAL_ERROR "You selected `${CMAKE_BUILD_TYPE}` mode. Only `Release` and `RelWithDebInfo` are supported.\nAdd -DCMAKE_BUILD_TYPE=Release or -DCMAKE_BUILD_TYPE=RelWithDebInfo to your cmake …
```

Add Errors with Tips and gitignore Clion.

---

src/gl.h
src/gl/deferred.cpp
src/lighting.cpp
src/renderer.cpp

I fixed the following bugs reported when lighting is enabled.
- Some elements of the battle UI not being drawn
- Depth buffer backup used for field shadows not working correctly in APIs other than DX11

Fixed Battle UI draw order and depth buffer backup

---

src/renderer.cpp

Fixed black screen after summons when lighting enabled. Added calls to disabled unintended framebuffer clears mid-frame.

Fixed black screen after summons when lighting enabled

---

misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff7/misc.cpp

I implemented analogue controls so that the player can move in whatever direction you move the joystick.
I used the "Control Direction" parameter in the flevel: http://wiki.ffrtt.ru/index.php/FF7/Field/Triggers
This parameter defines for each field the orientation the player moves. This PR achieves analogue controls by overriding this parameter every frame so that the player moves in 256 directions instead of 8.

FF7: Implemented analogue controls in fields

---

misc/FFNx.common.sh
misc/FFNx.frag
misc/FFNx.lighting.frag
misc/FFNx.lighting.sh
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/common.cpp
src/gl/gl.cpp
src/lighting.cpp
src/lighting.h
src/lighting_debug.cpp
src/movies.cpp
src/renderer.cpp
src/renderer.h
src/saveload.cpp
src/video/movies.cpp

This PR contains the following changes:
- Changed lighting so that it is done correctly in linear space instead of gamma space (SRGB). This requires a change to a RGBA16 framebuffer. Final SRGB conversion is done by adding the SRGB flag to the swap buffer. Textures that represent colors are set with the SRGB flag so it is converted to linear space by the GPU.
- Added functionality to load external environment maps for image base lighting (IBL).
- Added specular pbr parameter to control specular reflection of non-metallic materials
- Various shader code fixes

Implemented linear space and image based lighting (IBL)

---

src/audio.cpp
src/audio.h

To reproduce: read a psf file with the psf plugin unloaded (if you don't have configured a hebios, it is unloaded for example).
```
[00000003] ERROR: NxAudioEngine::loadMusic: Cannot load E:\Documents\Square Enix\FINAL FANTASY VII\satsuki\FF7SYW/music/psf/pre.minipsf with vgmstream
[00000003] TRACE: *** Exception 0xc0000005, address 0x784b220 ***
[00000003] TRACE: SymInit: Symbol-SearchPath: '.;E:\Documents\Square Enix\FINAL FANTASY VII\satsuki\FF7SYW;E:\Documents\Square Enix\FINAL FANTASY VII\satsuki\FF7SYW;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*https://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'myst6re'
[00000003] TRACE: OS-Version: 6.2.9200 () 0x100-0x1
[00000003] TRACE: E:\Documents\Square Enix\FINAL FANTASY VII\satsuki\FF7SYW\FF7.exe:FF7.exe …
```

Music: fix crash when a file cannot be opened by vgmstream

---

src/achievement.cpp
src/achievement.h
src/ff7.h
src/ff7/battle.cpp
src/ff7/defs.h
src/ff7/file.cpp
src/ff7/menu.cpp
src/ff7/misc.cpp
src/ff7_data.h
src/ff7_opengl.cpp

- Fix Gold Chocobo achievement by checking it when the slots are filled through some function under update_field_entities
- Fix Yuffie and Vincent achievement by checking it when the regular mask of the two character is modified
- Add FF7 variables to avoid unlocking some achievement randomly (unlock only when the condition actually switch from false to true)
- Move ff7_load_save_file function to misc.cpp

FF7Achievement: Fix and refactor FF7 achievements

---

src/achievement.cpp
src/achievement.h
src/common.cpp
src/ff7.h
src/ff7/battle.cpp
src/ff7/defs.h
src/ff7/menu.cpp
src/ff7/misc.cpp
src/ff7_data.h
src/ff7_opengl.cpp
src/movies.cpp

- Fix cait sith last limit achievement by checking the number of kills
- Fix bug in defeating weapons achievement by moving the check to the battle-end menu since fanfare sound is not played always
- Fix bug in mastered all materia in case the player takes one of the unmasterable materia
- Fix game progress achievement by unlocking them when the respective FMV movie plays
- Improve 1st limit break achievement by checking it during battle (these also unlock when 1-2 limit breaks are used)

FF7Achievement: Fix and improve Steam achievements

---

misc/FFNx.toml
src/achievement.cpp
src/achievement.h
src/cfg.cpp
src/cfg.h
src/ff7/menu.cpp
src/ff7/misc.cpp

- Allow unlocking last limit break achievement even when the item quantity is greater than 1
- Refactor FF7 steam achievement using constexpr and const reference parameters when possible
- Reorder FF7 achievement list to avoid using a list for swapping indices
- Add show achievement progress for materia overlord achievement
- Add debug flag in cfg for the future release of steam achievements

FF7Achievement: Release

---

src/achievement.cpp
src/achievement.h
src/common.cpp
src/ff7/misc.cpp
src/movies.cpp

This improves the end part 1 and end part 2 achievement since they will show after the menu screen of END PART (in which it allows you to save the game). For the end of game achievement, it has been moved to the end of "ending2" movie because the last movie ("ending3") is just before the game exiting which might avoid activating the achievement since it is not a sync call (unlocking the achievement at skip movies has been removed because the "ending2" movie cannot be skipped)
- Unlock end part 1 and 2 achievement through cd check after seen the respective last movie of each part
- Unlock end of game achievement on ending2 movie which is the one before the list of credits

FF7Achievement: Fix game progress achievement

---

src/cfg.cpp
src/common.cpp
src/ff7_opengl.cpp
src/movies.cpp

I've seen that steam_appid.txt is useless if run as steam edition. I also thought to activate steam achievements on steam edition directly (w/o looking at the flag in toml file), but maybe it is too soon.

FF7Achievement: Fix debug flag bug and avoid steam_appid.txt for steam edition

---

src/ff7.h
src/ff7/defs.h
src/ff7/menu.cpp
src/ff7_data.h
src/ff7_opengl.cpp
src/gamehacks.cpp
src/gamehacks.h

Add a new game hack for FF7 that enables auto attack mode. Each character will attack the 1st enemy. It can be activated outside battle and in-battle; even during the battle menu selection.

GameHacks: Add auto attack hack for FF7 battles (L2 + R3 or CTRL + A)

---

misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff7.h
src/ff7/camera.cpp
src/ff7/defs.h
src/ff7_data.h
src/ff7_opengl.cpp

This is what I have done on the camera 60 fps support. It is kinda a mess, but I have seen that it has the correct speed in the battle intro camera movement and also other things which I don't remember or cannot distinguish since the animations are quicker.
I have commented two lines in the ff7_opengl.cpp since they cause crashes, but they are in the original hext patch. While other two multiplication are missing because they cannot be done with this technique.

Support of correct camera speed at 60 FPS

---

src/ff7.h
src/ff7/camera.cpp
src/ff7/defs.h
src/ff7_data.h
src/ff7_opengl.cpp

- Fix horizontal camera rotation bug in one battle outro and other magic camera animation (opcode 0xF8)
- Patch opcode 0xE0 like the others (untested: still don't know where this is used)
- Refactor better camera script data structure

60FPS: Fix horizontal camera rotation bug and refactor

---

src/ff7.h
src/ff7/animations.cpp
src/ff7/battle.cpp
src/ff7/defs.h
src/ff7_data.h
src/ff7_opengl.cpp
src/voice.cpp

- Add voice support for display info about steal, mug, sense, ...
- Disable keeping display text until voice end for display info about steal, mug, and etc
- Add voice support for display action such as magic, limit breaks, ...
- Implement random choice of character playing voice during display actions

Voice: Add voice support for display action/info

---

src/ff7.h
src/ff7/animations.cpp
src/ff7/camera.cpp
src/ff7/defs.h
src/ff7_data.h
src/ff7_opengl.cpp

This new update should makes battle almost 60 fps non-progressive with glitches on camera and glitches when using summons. Testing right now is not really useful since there could be huge changes when tweaking the pause trick. If you need to group it as a single commit, feel free to tell me. I thought it was better to leave them as multiple commits since it is clearer.

60FPS Battle: Many fix and interpolation of battle animations, and implemented pause trick

---

src/ff7.h
src/ff7/animations.cpp
src/ff7/camera.cpp
src/ff7/defs.h
src/ff7_data.h
src/ff7_opengl.cpp

Now every summon in 60 fps mode should be running with no camera glitches and minimal animation glitches.
The second commit is the barebone for camera battle controls that Cosmos wanted

60FPS: Fix summon animation bugs and glitches + Add barebone for camera battle controls

---

misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff7/camera.cpp
src/ff7/camera.h
src/ff7/misc.cpp
src/ff7_opengl.cpp

I added analogue controls for the battle camera. You can rotate the camera with the controller right stick and zoom-in/ zoom-out with the analogue triggers. Controls are only enabled when no camera animation is being executed.

Implemented analogue camera controls in battle mode

---

src/common_imports.h
src/ff7.h
src/ff7/animations.cpp
src/ff7/animations.h
src/ff7/field.cpp
src/ff7/world.cpp
src/ff7_data.h
src/voice.cpp

Most of the spell, enemy moves, summons, and limit breaks effect should be interpolated. However there is a problem with some effect handler functions that calls the function I replaced with a "for" statement (probably particle effects), so, all those particles cannot be identified univocally.
I also fixed the encounter rate as it was too high for both WORLDMAP and FIELD mode. 
I added support for 30FPS battle using the same animation files, but the summons are not working since they do not have the 60FPS animation files. Could fix it in code by checking the actorID, but if in the future summon model will run in 60 FPS there is no need anymore.

60FPS: Interpolate animation effects about textures and materials (spells, enemy moves, ...)

---

misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff7/misc.cpp
src/joystick.cpp
src/joystick.h

Added camera zoom support for controllers without analog triggers as requested by Satsuki.
Also added analog deadzone options for the right stick and analog triggers.

Camera zoom for controllers without analog triggers and deadzone option

---

src/ff7/field.cpp
src/ff7_opengl.cpp
src/movies.cpp

- Fix partial animation (opcode CANM1, CANM2, CANIM1, CANIM2) wrong final frame value
- Fix scripted movement for field models by interpolating the position without checking for collision
- Fix FMVs animation for 60 FPS by removing script_ASPED modification because the problem was actually in non-interpolated animations

60FPS: Fix FIELD bugs and softlocks

---

src/ff7.h
src/ff7/animations.cpp
src/ff7/camera.cpp
src/ff7/field.cpp
src/ff7/misc.cpp
src/ff7/world.cpp
src/ff7_data.h
src/sfx.cpp

Mostly refactor of pointer array into spans and reordering of ff7_data.h. Then removing the bump to 60 FPS for chocobo, highway and submarine mode. Finally a lot of bugs, crashes fixes.

60FPS: Fix a bunch of bugs, crashes, and glitches

---

misc/FFNx.toml
src/cfg.cpp
src/renderer.cpp

This includes both a fix to how the recalcInternals function works as well as the new default value of 0 for the settings files.
A huge thank you to Cosmos for helping me get my tangled git branch all sorted so I could actually submit this PR as a single commit, as requested.  Unfortunately it did require closing the initial PR to resubmit.

recalcInternals fix and new defaults

---

src/ff7.h
src/ff7/field.cpp
src/ff7_data.h

This makes the movement of characters during split and join opcode like the OG 30 FPS, which should avoid softlocks related to this.
It also fixes a bug that made the movement during split and join even slower.

60FPS: Fix split and join opcode movement and rotation

---

src/ff7.h
src/ff7/animations.cpp
src/ff7/animations.h
src/ff7/defs.h
src/ff7_data.h
src/ff7_opengl.cpp
src/voice.cpp

60 FPS: Fix a softlock in battle and add support for summons interpolated animations (now it is possible to use interpolated summon animations since before the code related to that was running at 15 FPS).
Voice: remove for now implementation of support character voice since unneeded

60 FPS and Voice updates

---

src/common_imports.h
src/ff7.h
src/ff7_data.h
src/lighting.cpp

Thanks to vertex2995 we were able to get the view matrix used in movies. Using this matrix for field shadow rendering fixes the problem where shadows would not be rendered in their correct position.

FF7: Fixed field shadows in movies

---

src/lighting.cpp

Fixed field shadow crash when changing game modes. I reverted the pointer check for the level data that was there before and worked just fine.

FF7: Fixed field shadow crash when changing game modes

---

misc/FFNx.lighting.frag

Fixed a little mistake from the previous fix where it was setting the wrong output variable.

Lighting: Fixed lighting shader output

---

src/ff7.h
src/ff7/animations.cpp
src/ff7/field.cpp
src/ff7_data.h
src/field.h

This fixes all known minor issues in battle: 3D battleground movements (elevator, corel train, ...), yellow rotating mark on top of the head of the player, silence, confusion, and sleep animation effects, and also two display text frames length where strings are shown in battle

60 FPS: Minor updates on battle mode remaining interpolations

---

misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff7.h
src/ff7/camera.cpp
src/ff7/field.cpp
src/ff7_data.h

For example, it fixes the softlock in HoneyBee Inn bathtub

60FPS: Fix FIELD movement teleport glitch in special situations + Remove trace_battle_camera toml flag

---

src/ff7/field.cpp

There are specific occasions where the opcode of turngen and turn rotation is stopped in the middle of the execution. When using 60 FPS, the new `rotation_steps_idx` is not resetted to 0. This will cause a softlock since the `rotation_steps_idx` is greater than `rotation_n_steps` and it won't stop rotating. In original `rotation_steps_idx` this is resetted to 0, otherwise it won't start rotating, so to fix it we just set the new `rotation_steps_idx` to 0 at the start of the rotation.

60FPS: Fix new rotation steps index not starting from zero in specific situation

---

src/ff7.h
src/ff7/animations.cpp
src/ff7_data.h

Whenever Cid attacked in 60FPS, it played Cloud attack SFX due to a bug in Cid animation script and mismatch timing in 60FPS. This is fixed by removing this SFX from playing at all only in 60FPS

60FPS: Fix bug in Cid attack SFX

---

CMakeLists.txt
src/common.cpp
src/ff8.h
src/ff8/vibration.cpp
src/ff8/vibration.h
src/ff8_data.cpp
src/ff8_data.h
src/ff8_opengl.cpp
src/gamepad.cpp
src/gamepad.h
src/music.cpp
src/patch.cpp
src/world.cpp

FF8: Vibration feature

---

src/ff7/misc.cpp

Always find it strange that deadzone never worked. The value of rightTrigger and leftTrigger is actually in between `[0, 1]`. https://github.com/julianxhokaxhiu/FFNx/blob/master/src/gamepad.cpp#L114-L115

FF7: Fix deadzone bug for XINPUT analog triggers

---

Changelog.md
misc/FFNx.lighting.vert
src/ff7.h
src/ff7_data.h
src/ff7_opengl.cpp

Remove the special condition, in lighting vertex shader, used to skip original battle shadow that caused the field shadow triangle glitch

Lighting: Fix field shadow glitch for 3d models

---

misc/FFNx.varying.flat.def.sc
misc/FFNx.varying.smooth.def.sc

@CosmosXIII found this fix (https://www.opengl.org/pipeline/article/vol003_6/) for MSAA issue. This centroid evaluation is more computationally intensive and also less accurate, but it avoids the bad pixels. The best might be to use centroid evaluation only on 2D elements, but from testing, there is no much difference. For now, we could test and see what the users think and feel with this.
Since MSAA is no more problem, I increased the background position precision to 1/32. I don't think a higher precision is gonna make the background smoother.

60FPS: Fix MSAA tiles tearing by using centroid UV texture coords

---

src/ff7/field.cpp

This together with the centroid UV coordinate qualifier should avoid all tearing lines for whatever
combination of internal resolution scale (from 1x to 8x) and MSAA values.

60FPS: Set ideal precision to 1/10 for background positions

---

docs/shortcuts.md
src/gamehacks.cpp
src/gamehacks.h
src/gamepad.cpp
src/gamepad.h
src/joystick.cpp
src/joystick.h
src/log.cpp
src/log.h

Reworked gamepad shortcuts to prevent conflicts with game inputs.
I reworked the gamepad shortcuts to prevent conflicts with the game inputs. The new system works as follows;
- Press `L3` to enter shortcut input mode
- Press the newly simplified shortcut buttons:
- FMV Skip: `SQUARE`
- Battle mode toggle: `CIRCLE`
- Speedhack speed: `L1/R1`
- Speedhack toggle: `L2/R2`
- Soft Reset: `START + SELECT`
- Auto-Attack : `TRIANGLE`
You can also cancel the shortcut input mode at any time by pressing `L3` again.
Other than that I improved it so that you have to only wait 1 sec for the first input then it speeds up like with the keyboard.
Also it detects all button presses unlike before where inputs were ignored if you pressed the buttons too fast.

Reworked gamepad shortcuts to prevent conflicts with game inputs

---

src/ff7/animations.cpp

This is due to some timing issue that happens in 60 fps

60FPS: Fix model position glitch for some summons

---

src/ff7_opengl.cpp

Someone reported crash during loading save file for spanish version. I saw this clear bug since in `ff7_data.h` the spanish version uses the offset with `0xE9D`

FF7Achievement: Fix crash during load save file for spanish version

---

misc/FFNx.toml
src/cfg.cpp
src/common.cpp
src/common.h
src/ff7.h
src/ff7/battle.cpp
src/ff7/defs.h
src/ff7/field.cpp
src/ff7/widescreen.cpp
src/ff7/widescreen.h
src/ff7_data.h
src/ff7_opengl.cpp
src/patch.cpp
src/renderer.cpp
src/renderer.h

Added new 16:9 widescreen mode without stretching by modifying the projection matrix. This works for all parts of the game other than fields that do not have enough horizontal scrolling range to make it 16:9, the menus, movies and condor mode.
Below are the contributions by vertex (Thank you!!!)
- Decrease culling width range for 3D field models
- Fix fade quad size for FIELD mode
- Swirl framebuffer fix
- fixes: fading during start of battle, flashes done with quad, others
- Fix ifrit wave effect (only width)
- Fix Bahamut Neo backgrounds widths
- Fix 3D model unculling method
- Fix typhoon flashes effect widths
- Fix odin gunge lance flashes effect widths
- Fix effects for barret satellite beam and fat chocobo
- Add support for worldmap
- Fix shadow flare white background effect
- Fix …

FF7: Added new 16:9 widescreen mode without scretching

---

src/ff7.h
src/ff7/battle.cpp
src/ff7/widescreen.cpp
src/ff7/widescreen.h
src/ff7_data.h
src/patch.cpp
src/patch.h
src/renderer.cpp

This PR is meant to be merged after the main widescreen PR (#461).

FF7 Widescreen: Add support for highway, snowboard, chocobo, and credits mode

---

src/lighting.cpp
src/renderer.cpp
src/renderer.h

This PR fixes visual glitch when enabling both lighting and anti-aliasing.
By disabling the z-write for the field shadow draw call it works just fine so no need to backup/recover the depth buffer anymore.

Lighting: fixed visual glitch when enabling both lighting and anti-aliasing

---

src/common.cpp
src/common.h
src/gl.h
src/gl/deferred.cpp
src/movies.h
src/renderer.cpp
src/renderer.h
src/video/movies.cpp
src/video/movies.h

This PR fixes the framebuffer effects when lighting is enabled. 
The problem until now was that the blit draw call for the framebuffer effect was being executed at the wrong timing (before anything was drawn to the screen and therefore it was all black). By deferring the blit draw call in the same way as the other draw calls, we can reproduce the original intended order of execution. The same applies for the clear and movie rendering draw calls.
In other words, with this fix Titan finally found his floor :)

Lighting: Fixed draw call order for framebuffer effects

---

Changelog.md
src/ff7.h
src/ff7/field.cpp
src/ff7/world.cpp
src/ff7_data.h
src/voice.cpp

Fix FIELD and WORLD mode text box animation speed in 60 FPS. Also refactored a few of function names related to window text boxes.

60FPS: Fix FIELD and WORLD mode text box animation speed (opening, closing, next paging)

---

CMakeLists.txt
Changelog.md
misc/FFNx.blit.frag
misc/FFNx.blit.vert
src/cfg.cpp
src/cfg.h
src/common.cpp
src/ff7.h
src/ff7/field.cpp
src/ff7/widescreen.cpp
src/ff7/widescreen.h
src/ff7_data.h
src/gl.h
src/gl/deferred.cpp
src/renderer.cpp
src/renderer.h

This PR adds the logic to load and use a widescreen config file and implements a zoom logic to fill the 16:9 screen for fields that are not wide enough to extend all the way to 16:9. The changes of this PR are behind checks so that it only affects FF7.
Below is the work contributed by vertex:
- Widescreen: Add hook function just before draws related to text and text boxes
This will allow to increment the number of fields that can be displayed in widescreen mode and therefore improve consistency.
This is optional so when no config file is provided it will work as before.

Widescreen: Added config logic and zoom implementation

---

Changelog.md
src/ff7/field.cpp
src/ff7/widescreen.cpp
src/ff7/widescreen.h
src/gl/deferred.cpp
src/lighting.cpp
src/renderer.cpp

This PR adds the logic to offset the camera scrolling so that the camera movement can be adapted to better fit fields that use the zoom functionality.
These changes are done to improve the quality of camera movement in zoomed fields and only affects the widescreen mode when zooming is enabled through the config file.

Widescreen: Added logic to offset camera scrolling and minor other fixes

---

Changelog.md
src/ff7/field.cpp
src/ff7/widescreen.cpp
src/ff7/widescreen.h
src/movies.cpp
src/renderer.cpp
src/renderer.h

Added logic for vertical offset in movies and other minor widescreen fixes. The changes of this PR only take effect when widescreen mode is enabled.
This feature will allow to make movies 16:9 by zooming in a context dependent way so that the camera focuses on the important parts of the image

Widescreen: Added logic for vertical offset in movies and other minor fixes

---

src/common.cpp
src/gl.h
src/renderer.cpp
src/saveload.cpp

- Fix default handle index for DDS texture create (use FFNx one which returns 0 if not found)
- Remove as much as possible the number of reads on the texture file (Primarily the `stat` function check)
- Overhaul the texture loading by dividing clearly the animated texture loading and the normal texture loading.
Performance improvement for loading textures. The goal is to decrease the number of reads to the file. Instead of verifying the file existence, immediately try to load it. This reduce the number of reads on the file and it will return 0 if the texture file hasn't been loaded.
Also moved up the check for caching for animated texture. Also once an animated texture has been resolved (even with missing texture), this is saved on the hash table cache.
Due to performance issue in 7th …

FF7: Improve texture loading speed and caching

---

src/ff7/field/background.cpp

Fix #474 chocobo issue and fship_22 camera movement

Widescreen: Avoid clipping world Y position for FIELD mode world script movements

---

src/gl/special_case.cpp

Extend the width and x value of the buster texture (related to main menu when choosing new game or continue) only when `aspect_ratio` is AR_WIDESCREEN and the texture image has a ratio of 16/9

Widescreen: Extend x-axis vertices of buster texture vertices

---

src/voice.cpp

Add play voice for enemy actions in BATTLE mode. The file requested is `voice/_battle/enemy_XXXX/cmd_YY_ZZZZ.ogg` where `XXXX` is the enemy ID of the battle, `YY` is the command ID of the enemy, and `ZZZZ` is the action ID of the enemy. 
- enemy ID number is in in HEX format
- YY should be always 20. It's the command ID for enemy action
Echo-S mod seems to need it

Voice: Add play voice for enemy actions during BATTLE mode

---

src/ff7.h
src/ff7/field/field.cpp
src/ff7_data.h

Fix fading speed in FIELD screen transitions by decreasing a the fading speed for fade in and fade out.

60FPS: Fix fading speed in FIELD mode screen transitions

---

Changelog.md
src/ff7.h
src/ff7/battle/defs.h
src/ff7/battle/menu.cpp
src/ff7_data.h
src/ff7_opengl.cpp
src/gl/special_case.cpp
src/renderer.cpp
src/renderer.h

- Clear the frame buffer depth
- Add `bgfx::resetView` on all used viewId at each frame to avoid view collision at the next frame to allow to have dynamic number of views at each frame.
- Change logic to select battle UI elements to defer. Use a more clear condition.

Add clear depth on BATTLE mode before drawing UI (Related #131)

---

src/ff7/battle/menu.cpp
src/ff7/battle/menu.h
src/gl.h
src/gl/deferred.cpp

Fixes #131
The same fix as below but for lighting enabled:
https://github.com/julianxhokaxhiu/FFNx/pull/501
The motivation is to make Kuraudo happy. The expected outcome is Kuraudo being happy.

FF7: Fix 3D model drawn over UI on BATTLE mode if lighting enabled

---

Changelog.md
src/ff7/battle/camera.cpp

Fix fading out speed in BATTLE mode when exiting from battle mode. Also change generic type in few patches (just a refactor. Shouldn't change anything).

60FPS: Fix BATTLE mode outro fading speed

---

src/ff7/battle/menu.cpp
src/ff7/time.cpp

This PR fixes the time cycle filter not applying in battle mode.

FF7: Fixed time cycle filter not applying in battle mode

---

Changelog.md
src/ff7.h
src/ff7/battle/animations.cpp
src/ff7_data.h

With 60 FPS mod, when using Climhazzard against enemy with status (e.g. poison), can cause a crash. This crash does not happen always, but somehow "randomly". I do not know the real cause, but I just disabled any decorator wrapper on the battle effect function that cause the crash. After testing it more than 10 times, I didn't get any crash.
A user reported it.

60FPS: Fix Climhazzard random crash on poisoned enemy

---

src/ff7.h
src/ff7/battle/defs.h
src/ff7/battle/menu.cpp
src/ff7_data.h
src/ff7_opengl.cpp

Co-authored-by: Tangtang Zhou <5919707+tangtang95@users.noreply.github.com>
This PR fixes the time cycle filter applying over the action text box in battle mode.

FF7: Fixed time cycle filter applying over the action text box in battle mode

---

misc/FFNx.time.toml
src/ff7/time.cpp
src/ff7/time.h

This PR adds the logic to update a month string variable for the time cycle system.
This allows the month string update to be managed by FFNx instead of requiring a field script to update. It also allows it to be updated when in other modes such as battle and worldmap.

FF7: Added logic to update a month string variable for the time cycle system

---

src/renderer.cpp

Apply bgfx reset view only when it is FF7 and in battle mode.
The reset view caused a regression bug on FIELD mode where some text box when closed caused flickering. By applying the reset view only in battle mode, we avoid the issue and still keep this fix https://github.com/julianxhokaxhiu/FFNx/pull/508

FF7: Fix FIELD mode text box flickering rendering

---

Changelog.md
src/common.cpp
src/ff8.h
src/ff8/field/background.cpp
src/ff8/field/background.h
src/ff8/field/chara_one.cpp
src/ff8/field/chara_one.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/image/tim.cpp
src/image/tim.h
src/music.cpp
src/saveload.cpp

Adding field texture replacement for:
- Background
- 3D Models
Reducing texture upload allocations for both FF7 and FF8

FF8: field texture replacement

---

Changelog.md
src/ff8.h
src/ff8/texture_packer.cpp
src/ff8_data.cpp

- Jp version crash on start since the external SFX layer feature
- Fix a bad behavior when a texture is bigger than x10 the original size

FF8: Fix crash on JP version

---

src/common.cpp
src/common.h
src/ff7.h
src/ff7_data.h
src/ff7_opengl.cpp
src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp

- Fix FFNx logo game freeze by moving it before the squaresoft logo using the same timing logic (the consequence is the publisher movie will be before the FFNx logo)
- Add the ability to skip the FFNx logo, like the squaresoft logo
- Fix jp version + hook cleaning

Common: Use Game loop to render the FFNx logo

---

Changelog.md
src/audio.cpp
src/audio/openpsf/openpsf.cpp
src/audio/vgmstream/vgmstream.cpp
src/ff8.h
src/ff8/field/background.cpp
src/ff8/field/background.h
src/ff8/file.cpp
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/saveload.cpp
src/utils.cpp
src/utils.h

Try to load texture files from `field/mapdata/{first two letters of the field name}/{field name}/{field name}_{texture number}`
if the image from `field/mapdata/{field name}/{field name}` is not found.
+ PMP (field effects) texture replacement support at `field/mapdata/{field name}/{field name}_pmp`
+ Tiny improvements for VRAM texture replacements
+ adding helper functions to check if a file exist and to measure the elasped time a functions (in microseconds)
Existing mods on Tonberry or Demastered can have a lot of work to adapt for the background replacement mecanism in FFNx.

FF8: Enhance field texture replacement

---

Changelog.md
docs/ff8/mods/external_textures.md
docs/ff8/readme.md
docs/mods/external_textures.md
docs/readme.md
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff8.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/ff8_opengl.cpp
src/image/tim.cpp

- Adding ability to override textures from wmset section 39 (rails and roads), 40 and 42 (vehicles).
- Restore ability to mod "texl" textures, even with ff8_worldmap_internal_highres_textures option enabled. + bug fixes
- Add save_textures_legacy to save texture in legacy format instead of recommended one
- Fixes #565
- Texture reload hack mini optimization on worldmap

FF8: Add more overridable textures for Worldmap + fixes

---

Changelog.md
src/ff7/field/enter.h
src/ff7/field/model.cpp
src/ff7/field/model.h

There was a lot of reports of softlock when using 60 FPS on one of the last map of the game (https://github.com/julianxhokaxhiu/FFNx/discussions/569). This PR is to finally fix this softlock.
Save the poor players from rage quitting!

60FPS: Fix las0_5 map softlock in FF7

---

Changelog.md
src/common.cpp
src/ff7/field/field.cpp
src/ff7_opengl.cpp

Fix black color on field backgrounds
The PC rendering is different from the PSX rendering.
The PSX data clearly shows black pixels when the 15th bit is active in the 16-bit direct color (0x8000).
The PC version converted this black pixel to 0x0821 in data and at runtime it is converted again to 0x0403 (dark purple).
We also need to distinguish the black pixel to the transparent one using color key (0x0000).

FF7: Fix direct color

---

Changelog.md
src/ff8/texture_packer.cpp
src/ff8/vram.cpp

Fix crash with external texture replacement. When replacing battle stage background, I detected a crash by using Quezacotl.

FF8: Fix crash with external texture replacement

---

misc/FFNx.toml

Provide instruction on proper use of data_drive directive in FF8
I choked on it tonight figuring "F" was good enough, then Windows barfed on me for attempting "F:\\"

Improve clarity of data_drive usage

---

src/ff7/battle/animations.cpp
src/patch.h

Fix crash in battle mode when using 30fps mod and ESUI mod
Because yes!

30FPS: Fix crash conflict in FF7 with ESUI mod

---

src/ff7.h
src/ff7/battle/animations.cpp
src/ff7/battle/menu.cpp
src/ff7/battle/menu.h
src/ff7_data.h

In 60 FPS battles, currently the status menu skips the character status when a character has more than one status. 
This patch fixes it.
💯

60FPS: Fix char status menu rendering speed in FF7

---

Changelog.md
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff8/battle/stage.cpp
src/music.cpp

Fix battle stage texture dump with save_textures on.
option to use music files from remastered => if you extract the ogg files from remastered archives, you obtain files named like:
- 008s-antena.ogg
- 018s-julia.ogg
It is the same format as the original game, but the extension is replaced from sgt to ogg. Also this does not use xg files naming
I expected at first that Roses and Wine mod was using the same file name pattern than the original game.
That's not the case, we need to maintain a list of filename, that I don't want to.
But as a quickwin I can add the option for users who want to import oggs files from the remastered version to the 2013 version.

FF8: Fix battle stage texture dump + option to use music files from remastered

---

src/ff7/battle/animations.cpp
src/patch.h

This reverts commit e0173f7d0652f63f0849e961f565d087eb53b419.
This fix does not work well. It fixes the crash with ESUI + 30fps + 4:3, but it introduces a crash with ESUI + 30/60fps + 16:9. So, it might be better to revert it. 
I think ESUI compatibility with widescreen and 60fps works by luck. There might be a lot of other conflicts.

Fix: Revert "30FPS: Fix crash conflict in FF7 with ESUI mod (#592)"

---

src/ff7.h
src/ff7/battle/animations.cpp
src/ff7/battle/menu.cpp
src/ff7/battle/menu.h
src/ff7_data.h
src/ff7_opengl.cpp

Related to https://github.com/julianxhokaxhiu/FFNx/pull/592 and https://github.com/julianxhokaxhiu/FFNx/pull/593. This refactoring of battle menu 60fps fix follows the approach used in 30fps. It requires less patches and it should give better results in compatibility and coherence. 
Also in the second commit I put a workaround for 30 fps + ESUI. I am not really a fan of it, but it does the job.

FF7: Refactor 60FPS battle menu fix and fix ESUI compatibility

---

Changelog.md
src/common.cpp
src/ff8.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp

- Fix texture blending when using mods
- Fix mods removed after showing menu.
- Continue to use high-res WM when save_textures is enabled
- Fix alpha in dumped monster textures.

FF8: External texture fixes

---

Changelog.md
src/common.h
src/ff8/field/chara_one.cpp
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/uv_patch.cpp
src/ff8_data.cpp
src/renderer.cpp
src/voice.cpp
src/world.cpp

- Non-us version does not use similar addresses in Worldmap.
- When an external texture contains an almost opaque alpha, like 254, the pixel is displayed black, force an opaque color to show the real color of the pixel instead
- texl textures (high res worldmap textures) can only be upscaled to 1024x1024, because source height is incorrect. But it should be incorrect as it replaces low res worldmap textures. So I decided to increase MAX_SCALE a lot. Now it is possible to upscale texl to 16384 (which is the max texture size on my machine).
Crash => no crash

FF8: Increase max texture size to 16384 for external textures + Minor fixes

---

Changelog.md
src/gl/gl.cpp

Fixed Bahamut Zero and Supernova not displaying correctly when lighting enabled. The lighting shader assumes an input with valid normals. So for any model that has no valid normals I changed it to fallback to the standard shader.
Because it's time to have a bug-free lighting mode from start to finish :)

FF7: Fix Bahamut Zero and Supernova not displaying correctly with lighting

---

Changelog.md
src/gl/deferred.cpp

Fix for field shadows not displaying during FMV movies. Problem was the projection matrix was not being set correctly.
To clean Cosmos own mess.

FF7: Fix field shadows not displaying during FMV movies

---

Changelog.md
misc/FFNx.lighting.toml
misc/FFNx.pcf.sh
src/lighting.cpp
src/lighting.h
src/lighting_debug.cpp

Fixed minor shadow visual glitches occurring in some fields like shadow stretching or some unintended shadows appearing where they shouldn't. Changed also the lighting config save to only be done when a parameter has been modified (until now every field loaded was creating config entries).
To make people happy.

FF7: Fixed minor shadow visual glitches occurring in some fields

---

Changelog.md
src/ff7.h
src/ff7/battle/animations.cpp
src/ff7/widescreen.cpp
src/ff7_data.h
src/matrix.h

Fix widescreen glitches (related to #474) for:
- Bahamut Zero stars background positioning and size
- Pollensalta cold breath attack: moving background and moving white dots 
Regarding Pollensalta fix for the moving background size: this only works when in 30/60fps mode because I used a function hooked only when in 60 fps mode. I don't think there is other way to do it, but I think the correct solution should be to fix the texture page which I suppose it is inside files with `.s` as extension (in this case, `special/hubuki/kemu.s`). So I left the solution for 30/60fps just as a temporary fix.
I don't know why either

FF7: Fix Widescreen glitches for Bahamut Zero and Pollensalta

---

Changelog.md
src/ff7.h
src/ff7/widescreen.cpp
src/ff7_data.h

Another widescreen fix on battle mode: Pandora Box white background position (related to #474)
Again...Sorry should have put this change into the previous PR

FF7: Fix Widescreen Pandora Box white background position

---

Changelog.md
src/ff8.h
src/ff8/field/chara_one.cpp
src/ff8/vram.cpp
src/ff8/world/chara_one.cpp
src/ff8/world/chara_one.h
src/ff8_data.cpp

Add worldmap texture replacement for Squall, Zell, Selphie (?), Ragnarok and Chocobo

FF8: World chara.one textures replacement

---

Changelog.md
docs/ff8/mods/external_textures.md
src/common.cpp
src/ff8.h
src/ff8/mod.cpp
src/ff8/mod.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/ff8_opengl.cpp
src/image/image.cpp
src/image/image.h
src/image/tim.h
src/renderer.cpp
src/renderer.h

- Support for dynamic palette changes of the same texture.
- Separation of texture identification code and texture modding code
- code to open images (PNG or bimg supported formats) is moved outside the renderer
- Optimization of mod (and game!) texture loading time
For example the minimap in the worldmap module.
In the future we want to bring at least compatibility with the remaster. Separating texture identification part permit reuse and clarity.

FF8: Add support for palette changes in external textures + optimizations

---

Changelog.md
src/common.cpp

There was a typo in code (probably a copy-paste) error that made it so music volume might've been never loaded in some circumstances.

Sound: Fixed a typo when reading sound configuration in FF7

---

Changelog.md
src/common.cpp
src/ff7.h
src/ff7_data.h
src/ff7_opengl.cpp
src/sfx.cpp

Fixes issue #623 by disabling the ability to change the Controller setting to "Normal". This is what Aali driver originally did and this change apparently wasn't ported to FFNx.

FF7: Fix a softlock when trying to change in-game Controller setting to "Normal"

---

Changelog.md
src/common.cpp
src/ff7_opengl.cpp

Fixes issue #622 by patching out functions that enable direct keyboard input on character naming screens. This is what Aali driver originally did and this change apparently wasn't ported to FFNx. See linked issue for more details.

FF7: Fix character naming screen not working correctly when Steam Input is enabled

---

Changelog.md
misc/FFNx.toml
src/common.h
src/ff8.h
src/ff8/battle/stage.cpp
src/ff8/field/background.cpp
src/ff8/vibration.cpp
src/ff8/world/wmset.cpp
src/ff8_data.cpp
src/ff8_data.h
src/ff8_opengl.cpp

Send analog input to the core game. Per module, not globally, because analog already works well as a d-pad.
- Field module: send analog values for characters movements (it automatically overrides d-pad input sent by the driver)
- World module: send analog values for everything (left and right sticks), but override d-pad input only for characters movements
PlayStation version always supported analog input for character movements, not only 8 directions, but a range of 255*255 values.
The game also implements an auto walk/run feature depending of the strength of the analog input.
Finally in worldmap, vehicles can be driven using the right stick along with the left stick.
https://finalfantasy.fandom.com/wiki/Final_Fantasy_VIII_version_differences#Microsoft_Windows

FF8: Enable 360 analog input

---

Changelog.md
README.md
src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp

In PC version (original and Steam), the SFX ids for Quezacotl are thoses used for Phoenix.
This patch fixes this

FF8: Fix Quezacotl SFX

---

Changelog.md
docs/shortcuts.md
src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp

The intro credits (before the main menu) is not synchronized with the background music.

FF8: Fix intro credits unsync

---

Changelog.md
misc/FFNx.lighting.toml
src/ff7/battle/camera.cpp
src/ff7/field/background.cpp
src/ff7/field/camera.cpp
src/ff7/field/camera.h
src/ff7/misc.cpp
src/ff7_opengl.cpp
src/lighting.cpp
src/lighting.h
src/renderer.cpp

This PR adds the functionality to scroll the camera with the right analog stick. The camera goes back smoothly to it's usual position once the analog stick is released.
This PR also has some other minor fixes.
- Fixes the problems raised in #460 -> was not able to reproduce the bugs but this should be safer than before
- Reduced lighting specular because it was too washed-out in some places
Because we need more rainforest, not less, I'm serious.

FF7: New camera control in field mode using the right stick

---

Changelog.md
src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp

As a french player, the first thing I see when I start the game is a bug. Enough is enough, let's restore the reputation of FF8 once and for all!

FF8: Fix main menu texts on new game

---

Changelog.md
src/common.cpp
src/ff8/mod.cpp
src/ff8/texture_packer.cpp

- Common: hide cursor when starting the game in fullscreen
- FF8: Fix Tonberry layer

FF8: Fix Tonberry layer

---

Changelog.md
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp
src/joystick.cpp
src/joystick.h

FF8: Add option to display playstation icons

---

Changelog.md
src/renderer.cpp

Fixed fog being incorrectly applied to Emerald Weapon battle. The problem was that the fog flag was not being reset.
Because otherwise can't see shit.

FF7: Fixed fog being incorrectly applied to Emerald Weapon battle

---

CMakeLists.txt
Changelog.md
src/common.cpp
src/ff8.h
src/ff8/mod.cpp
src/ff8/mod.h
src/ff8/texture_packer.cpp
src/ff8_data.cpp
src/ff8_opengl.cpp
src/image/image.cpp
src/image/image.h
src/renderer.cpp
src/renderer.h
vcpkg.json

- Fix gamepad icons not displayed
- Use libPNG to decode PNGs, instead of bimg
- Use DirectXTex to decode DDS and decompress only the relevant lod for faster loading
- Minimize memory allocations with external textures to allow bigger textures and prevent game crashes (the game is limited to 2GB if not patched, and 4GB if patched, due to its x86 nature)
Fix things

FF8: Various enhancements and fixes

---

Changelog.md
src/ff7/world/camera.cpp

Preserve world camera state when changing game modes to prevent resetting after every battle, when entering menus or coming back from a field.
Because resetting every time was very annoying.

FF7: Preserve world camera state when changing game modes

---

.github/workflows/build.ps1
Changelog.md
docs/ff8/mods/external_textures.md
misc/FFNx.toml
src/ff8.h
src/ff8/mod.cpp
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/ff8_opengl.cpp

Rewrite metadata file when a save file is created to prevent save file loss.
Currently the metadata file is updated when the game is closed. Some users experienced save file loss, maybe because the metadata file was not updated correctly and the ff8 launcher removed the save files which were detected as invalid.
Losing your save is very serious situation, I never finished the game Child Of Light because Ubisoft devs do not understand the concept of redundancy and do not let you create several saves. Crash, lost hours, cry a lot, bargain, accept.

FF8: Update metadata file when a save file is created

---

Changelog.md
src/ff7/world/player.cpp

Fixed menu not working when using the buggy and external worldmap. For some reason the world_is_player_model_bitmask function does not work so instead I made it check the model id values manually.
To return the original behavior where the player can use the menu while using the buggy.

FF7: Fixed menu not working when using the buggy

---

src/ff7/world/player.cpp

Fixed menu not working when using external worldmap mesh again because my previous fix was incorrect.
To fix my own mess

FF7: Fixed menu not working when using external worldmap mesh

---

Changelog.md
src/ff8_data.cpp
src/ff8_opengl.cpp

Bad address for the jp version only

FF8: fix JP Steam crash

---

Changelog.md
src/ff7/field/background.cpp
src/ff7/widescreen.cpp
src/ff7/widescreen.h

Fixed scripted camera clipping when widescreen enabled.
So that camera does not do weird jumps or goes beyond borders when using widescreen.

FF7: Fixed scripted camera clipping when widescreen enabled

---

Changelog.md
src/ff7/misc.cpp

Fixed auto-run not working sometimes on diagonals. The reason being that x and y values get smaller on diagonals, it needs to use the vector length instead.
Because the player speed gets unstable depending on the input direction.

FF7: Fixed auto-run not working sometimes on diagonals

---

Changelog.md
src/ff7/world/camera.cpp
src/ff7/world/player.cpp
src/ff7/world/world.cpp

Fixed not being able to place the flags during snowstorm. PR also includes some minor adjustments to worldmap controls and disables unintended shadow rendering in snowstorm map.
Because that part of the game is annoying enough already.

FF7: Fixed not being able to place the flags during snowstorm

---

Changelog.md
src/ff8.h
src/ff8/vibration.cpp
src/ff8_data.cpp

Bring back Vibration option in the main menu and the battle pause menu.
The vibration option was restored only in field and worldmap pause menus. Since it is common that user want to disable vibration in battle, it is great to restore the original pause menu in battle too.
_ePSXe french_
_FFNx french enabled_
_FFNx french disabled (keyboard or gamepad without rumble capability)_

FF8: vibration option in main menu

---

misc/FF8.reg
src/ff8/mod.cpp
src/ff8/texture_packer.h

- When the external texture is upscaled (which is the common case), texture copy is not scaled up to the full size of the copy
- Adding some rules in the .reg file to allow alt+tab and windows key press (FF8 2000 only). It will ask Windows to disable all compatibility patches, which are not needed anyway with FFNx

FF8: Fix texture animation only partially animated

---

Changelog.md
misc/FFNx.music.toml
src/audio.cpp
src/audio.h

External Music: ability to set music speed via config
Kurodo asked me if it was possible to sync "tb" music track (main theme alternative / Cloud's mind) with the scene, like in PS1
https://www.youtube.com/watch?v=ELt0-heDj0I&t=20020s
The PC version is faster than the PSX version, one solution would be speed up the music. That's increase the pitch a little, I'm not a big fan of this solution. But everyone seems fine with it, for example the modder Postscriptthree released a fix that just does just that, DLPB also did this in the past.
Since this patch is really light, and can be used by modders for whetever creative reasons (I enjoy listening to the slow version of costa del sol, for example), so let's do it!

Music: Add new relative_speed option in the config layer

---

Changelog.md
src/ff8.h
src/ff8/battle/effects.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/image/tim.cpp

We try to ensure textures are correctly named in battle
and some textures hidden in mag.0/mag.1... files are now replaceables.
Some of those textures may not be dumped correctly with "save_texture" option, I added some "guessed colors" dumps to help modders for now.

FF8: Allow more external texture replacement for battle effects

---

Changelog.md
src/ff8.h
src/ff8/battle/effects.h
src/ff8/vibration.cpp
src/ff8_data.cpp

Use the current magic id to identify battle vibrate sequences
Vibration config file are not named with hashes anymore, but with the magic id like this:
```
battle_effect_{magicID}.toml
```
There are several pools of vibration sequences:
- the common one (for the pause menu)
- the field one (for setvibrate opcode)
- the world one (for vehicles)
- and a lot for battle effects
Before this PR I wasn't able to identify which battle effect is linked to which vibrate pool.
So I used hashes over the data to identify most of them.

FF8: Do not use hashes to name vibration config files

---

Changelog.md
src/ff8/vram.cpp

Some effects still have issues to get overriden correctly.
- Doomtrain (and maybe some others): first texture is not named correctly, we use the filename of the last loaded weapon
- Cerberus/Cactuar (and maybe some others): some textures are not dumped, because we don't have any palette 
- Carbuncle: We assumed that a tim file contains only one texture, that's not the case for Carbuncle
- Effect Tims with multiple palettes: dump all the palettes
To please digixu

FF8: Battle effects external textures improvements

---

Changelog.md
src/ff8/vram.cpp
src/saveload.cpp

Magic textures wrongly dumped when save_textures option is disabled.
**Important:** If you have installed [FFNx-v1.19.0.0](https://github.com/julianxhokaxhiu/FFNx/releases/tag/1.19.0), please remove the directories `mods/Textures/battle` and `mods/Textures/magic` and reinstall your battle mods if you had any.

FF8: Magic textures wrongly dumped when save_textures option is disabled

---

Changelog.md
src/image/image.cpp

Ignore PNGs without alpha (for now)
Converting PNGs adds a little overhead, it is not big, but we don't want to promote PNGs in mods

FF8: Fix game over crash with external textures

---

Changelog.md
docs/ff8/mods/external_textures.md
src/common.cpp
src/ff7.h
src/ff8.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/ff8_opengl.cpp
src/image/tim.cpp
src/image/tim.h
src/saveload.cpp

Allow mod textures per VRAM page. This is like how [Tonberry](https://forums.qhimm.com/index.php?topic=15945.0) works, but no hashes needed.
File name format: the vram page id is added and if there are several textures in the vram page, most of them are put in the filename `{texture_names}_{vram page id}_{palette x}_{palette y}`
Example: `A0STG101.X-0_16_0_255`
Even if VRAM pages are fragmented and can contains several unrelated textures, they could be useful for modders.
- They are GPU accelerated, meaning that DDS files are uncompressed on the GPU without blocking the CPU
- Some part of some big textures could be reduced in size, especialy in battle where some VRAM pages are animated, and other not
- A lot of existing mods could be ported easily to FFNx

FF8: Allow mod textures per VRAM page

---

Changelog.md
docs/ff8/mods/external_textures.md
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/common.cpp
src/ff8/mod.cpp
src/ff8/mod.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_opengl.cpp
src/gl.h
src/gl/special_case.cpp
src/saveload.cpp

- External textures: Reuse already loaded textures on fallback to palette 0
- External textures (FF8): Optimize field external textures support (Tonberry Mods layer)
- Rendering: Add bilinear filtering option `enable_bilinear`
Sometimes for the same texture, there are many palettes. In the graphic driver, we do not upload palettes anymore, and external textures often does not need one texture per palette, but are optimized to one texture for all palettes.
In this case, it is interesting for performance that this "one texture" is opened from disk and uploaded to gpu only once. And if the game try to upload the same texture, but with a different palette, it could detects this case and just reuse the already uploaded texture.
If was asked by few users. For now I just added the option with a …

Common: Bilinear filtering + external texture optimizations

---

Changelog.md
src/audio.cpp

Fix sudden stop of musics, for example in Fisherman Horizon Concert, when the dialog starts with Rinoa next to the stage.

Audio: Ensure Voice handle exists before stopping it

---

Changelog.md
src/ff7/field/background.cpp
src/ff7/widescreen.h
src/gl/gl.cpp

Added feature to extend movies in true widescreen mode. This mode can be enabled/disabled per individual movie on the widescreen movie config file.
To make Satsuki happy and save the planet.

FF7: Allow movies to be extended to true widescreen mode

---

Changelog.md
docs/ff8/mods/external_textures.md
docs/mods/direct_mode.md
docs/mods/exe_data.md
docs/readme.md
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/common.cpp
src/exe_data.cpp
src/exe_data.h
src/ff8.h
src/ff8/battle/effects.h
src/ff8_data.cpp
src/saveload.cpp

Sometimes texts and textures are stored inside the EXE, instead in the data directory.
In this case it is harder for modders to mod the game.
This feature allows modders to override data from the EXE via the
Direct Mode feature.
Use the `save_exe_data` option to dump files to the direct/exe/ directory.
And then FFNx will look for those files directly instead of data from the EXE.
- `battle_scans.msd`: Texts in battle scans. Note: this is not exactly the same
format in the EXE, the msd format is used because it is a well documented format
of FF8.

Modding: Allow replacing EXE text/data hardcoded in code

---

Changelog.md
src/ff7.h
src/voice.cpp

When battle text speed is set to max SLOW (far right), battle text popup (e.g. messages after doing a steal) will behave like it is fast due to an integer overflow when casting int to char. 
This has been fixed by fixing the data type which should have been unsigned char and just for safety, I have added also a minimum to avoid even an unsigned char overflow.
Better experience in 60 FPS

FF7: fix 60FPS battle text when text speed is set to max SLOW

---

Changelog.md
src/ff7/field/background.cpp
src/ff7/widescreen.cpp
src/ff7/widescreen.h

Added option to clip camera position during scripted events. This will be use to fix scenes where the camera goes beyond the boundaries showing black empty space.
Save the planet.

FF7: Add option to clip camera position during scripted events

---

Changelog.md
src/common.cpp
src/ff8.h
src/ff8/file.cpp
src/ff8/file.h
src/ff8_data.cpp
src/game_cfg.cpp
src/redirect.cpp
src/redirect.h

Enable override_path option for FF8
`override_path` option in FF7 allows modders to put files and LGP archives in another directory than the game data.
It is quite useful when a modder want to edits LGP archives without change original files from FF7 installation.
The FF8 version is basically the same thing, but simpler: any file that is opened by the game (for reading or writing) is firstly checked in the `override_path`. For example for `.\ff8input.cfg`, FFNx checks for the existence of `.\override\ff8input.cfg`, and for `.\Data\field.fs`, FFNx checks for the existence of `.\override\Data\field.fs`, and so on.
The Steam version of the game try to look to some files like saves in Documents/Square Enix (the user directory), for the lack of simplicity and uniformity between the 2000 and …

FF8: Enable support for the override_path option

---

Changelog.md
src/ff8/texture_packer.cpp
src/game_cfg.cpp
src/gl.h

Two fixes:
- When battle is partially modded, non modded textures could use the wrong palette. This happens because the new cache conflict between the two ways of modding
- mkpath does not work anymore on ff8, because the wrong sub is called to uniformize paths

FF8: Fix wrong palette for external textures on battle and wm

---

docs/ff8/mods/external_textures.md
src/ff8.h
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h
src/ff8/vram.cpp
src/ff8_data.cpp
src/ff8_opengl.cpp

- Support rect copy animation and force palette id animation
- Optimize texture reload hack
- Fix conflict between texture caches when modding battle and worldmap (which leads to bad colors in non-replaced textures)
Why are you doing this? What use cases does it support? What is the expected outcome?

FF8: Add animation support for per VRAM page texture replacement

---

Changelog.md
src/ff8/texture_packer.cpp
src/ff8/vram.cpp

Field background mods broken again since texture_reload_hack was tuned to minimize texture uploads on worldmap

FF8: Fix field bg mods reload hack

---

Changelog.md
src/common.cpp

Make Creative EAX Unified as an optional dependency
+ search the eax.dll in ./creative_eax.dll before searching in system dir
On the 2000-version, eax.dll is replaced by FFNx, but the original eax.dll is still mandatory, as it is used to instanciate DirectSound.
On today hardware, EAX does nothing special, so it seems fair to partially remove this dependency.

FF8: Make Creative EAX Unified as an optional dependency

---

Changelog.md
src/common.cpp
src/globals.h
src/movies.cpp

The first argument passed to ff8_prepare_movie(disc, movie) was often (or always?) strange. There was a workaround on the Steam version, but the main question remains: why the disc id is so weird?
The answer is simple, that's because it should be a unsigned char, not a unsigned int.
Fixes #730

FF8: Fix FMV filenames when enable_ffmpeg_videos = true

---

Changelog.md
src/movies.cpp
src/redirect.cpp
src/redirect.h

- Move app_path back to movies, but only if the redirection failed.
- Document the redirection return values, and force redirect_path_with_override to return 0 only when a redirection happened
file redirection works on relative paths, so @julianxhokaxhiu moved the app_path outside the movies logic to the redirection logic.
But if we do this, redirection will be relative to app_path, which I don't want, because app_path is reserved for game data, not mods.

FF8: Fix app_path configuration for movies

---

Changelog.md
src/ff8/file.cpp

My implementation was wrong, decompression data start 4 bytes further.

FF8: Fix LZ4 decompression

---

Changelog.md
docs/mods/exe_data.md
src/common.cpp
src/gl/gl.cpp

- Fix elevator blending for mods
- Fix crash when more_debug option is enabled -> replacing OutputDebugStringA was a bad idea and leaves the game in a undefined state

FF8: Fix elevator blending for mods #746

---

Changelog.md
src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp
src/voice.cpp

Fixes #693 and more
**Bring back shadows and tinted window**
_Elevator window is darker_
_Shadows are back_
**Battle transition + shadows**
https://github.com/user-attachments/assets/674a7e17-cfd7-48ae-b84d-d32bb228cd5a
**Field transition**
https://github.com/user-attachments/assets/f26643be-1462-439a-bd11-076ec4b18471
Substractive blending is enabled only if the graphic driver is software and use paletted textures.
Unfortunately Battle transition (from worldmap at least) suffer from this change

FF8: Bring back shadows and tinted window

---

Changelog.md
src/renderer.cpp

Fix crash when there is not enough RAM. Fixes #726

Common: Fix bgfx crash when there is not enough RAM available

---

Changelog.md
src/common.cpp

Fix external texture reload when different textures uses the same texture set
https://github.com/julianxhokaxhiu/FFNx/issues/759

FF8: Fix external texture reload #759

---

Changelog.md
src/ff7/file.cpp

So since i don't typically run gameplay mods, i missed a crash i caused by trying to use known_field_buffer_size to calculate the actual size of chunk 11.  Even trying to do this causes stuff to be written outside the buffer, which is bad.  Since ffnx doesn't have it's own decompressor, i can't get the real size. so I have no choice but to trust the section header.
Fixing what I broke.

FF7: Fix field chunk size calculation for the chunk number 9

---

Changelog.md
misc/FFNx.toml
src/cfg.cpp
src/cfg.h
src/ff7/field/background.cpp
src/ff7/field/enter.h
src/ff7/field/field.cpp
src/ff7/field/utils.h
src/ff7_opengl.cpp
src/renderer.cpp

Added uncrop option to remove black bars from top/bottom of the screen. This can be used to uncrop the screen even when using 4:3 aspect ratio or for not widescreen extended screens in 16:9 mode.
So that people that prefer almost squared stuff can be a little more happy.

FF7: Add option to remove top/bottom black bars on the screen

---

src/common.cpp
src/renderer.cpp

Fixed right side of screen being clipped during movies when uncrop option is enabled. 
To fix a bug reported by a user.

FF7: Fix movies being clipped when uncrop option is enabled

---

src/ff7/menu.cpp

Brief explanation of the pull request.
Make Auto Attack use equipped commands like 4x cut or slash-all.
Why are you doing this? What use cases does it support? What is the expected outcome?
Someone asked me to. It makes auto attack more useful. It also brings functionality in line with berserk, which respects your equipped attack command.

FF7: Use equipped Attack behavior when using auto-attack shortcut

---

Changelog.md
docs/mods/exe_data.md
src/exe_data.cpp
src/ff8.h
src/ff8_data.cpp

Add Triple Triad texts and draw spell texts to exe data feature
Helping translating the game

FF8: Add Triple Triad and draw spell texts to exe data feature

---

Changelog.md
src/ff8.h
src/ff8_data.cpp
src/ff8_opengl.cpp

When ff8_use_gamepad_icons is enabled, the red cross is not visible in gf boost ability

FF8: Fix GF boost icons when ff8_use_gamepad_icons is enabled

---

Changelog.md
src/ff8/texture_packer.cpp
src/ff8/texture_packer.h

Rinoa battle texture is 97 px height instead of 96, and get removed from the modding grid when another texture (Rinoa's weapon) is uploaded below this texture.
I added a tolerance for this special case to not clear a texture (at least 10x10 px) that get overlapped with only 1 px.
To mod Rinoa's model in battle

FF8: Fix texture modding for Rinoa battle model

---

src/ff7.h
src/ff7/battle/animations.cpp
src/ff7_data.h

Fix escape magic animation speed to 15 FPS. The logic behind is too complex to try to make those animations run at 60
Fix #794

FF7 60FPS: Fix escape magic animation speed to 15FPS

---

src/ff8/save_data.h
src/movies.cpp
src/voice.cpp

Fix issue of triple triad where selecting a card would select another one or when obtaining a card
Bug

FF8: Fix triple triad card index issue and achievements stuff

---

src/ff7.h
src/ff7/battle/animations.cpp
src/ff7_data.h

Fix escape magic animation speed for 60 FPS
Fix #794

FF7 60FPS: Fix escape magic animation speed to 60FPS

---

Changelog.md
src/ff8.h
src/ff8/file.cpp
src/ff8/file.h
src/ff8_data.cpp
src/ff8_opengl.cpp

Currently direct file is not possible for subarchives. In field.fs, there are other *.fs files stored, currently we can only use direct file for files inside the *.fs subarchives, not the *.fs archive itself.
A good use case is when we want to add new field maps in a mod, the game needs *.fs subarchive to exist

FF8: Allow to load fs subarchives using direct_path

---

Changelog.md
src/ff8_data.cpp
src/ff8_opengl.cpp
src/field.cpp

New crashes in JP version with the recent changes

FF8: Fix crashes in JP version

---

src/cfg.cpp
src/renderer.cpp

Enabled preliminary support for true widescreen in FF8.
I heard there is a witch that needs to be stopped.

FF8: Preliminary support for true widescreen
